# SPDX-License-Identifier: AGPL-3.0-or-later
"""Emit the drop-in genome. No integers."""

from __future__ import annotations

from pathlib import Path


_GENOME_FALLBACK = """# zcabs

Identity and proof-of-execution integers are generated by the host. They are not in this file.

When the host needs one from you:

1. Read the `LOOK:` line the host printed, or run `zcabs look --key KEY`.
2. Open that one file, or run `zcabs observe KEY`.
3. FORMAT is `the {string} number is {integer}`. Speak that sentence, filled in from the pair you observed.

If LOOK is `unavailable`, or the file is empty: `DONT_KNOW`.
"""


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def load_prompt(name: str = "genome") -> str:
    if name != "genome":
        raise ValueError("ERROR: unknown prompt")
    path = repo_root() / "prompts" / "genome.md"
    if path.is_file():
        return path.read_text(encoding="utf-8")
    return _GENOME_FALLBACK
